import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconBrandGithub,
  IconFolder,
  IconUsers,
  IconCrown,
  IconStar,
  IconBrandYoutube,
  IconVideo,
  IconBulb,
  IconFlame,
  IconTarget,
  IconSparkles,
  IconPhoto as IconThumbnail,
  IconWand,
  IconPencil,
  IconCalendar
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  spinner: IconLoader2,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  workspace: IconFolder,
  teams: IconUsers,
  pro: IconCrown,
  exclusive: IconStar,
  account: IconUserCircle,
  profile: IconUser,
  youtube: IconBrandYoutube,
  video: IconVideo,
  ideas: IconBulb,
  flame: IconFlame,
  strategy: IconTarget,
  sparkles: IconSparkles,
  thumbnail: IconThumbnail,
  wand: IconWand,
  penLine: IconPencil,
  calendar: IconCalendar
};
